### ISSUE TITLE
Organize List of Vascular Malformations order by rarity

### ISSUE THREAD

**Issue by brunasv** [brunasv/ISSVA#10]
currently:
Combined
Provisionally Unclassified
Simple
Major vessels
associated

should be: 
Simple
Combined
Major Vessels
Associated.
Provisionally Unclassified

**Comment by martijnkersloot** [comment]
Add this as a property (numeric property 1-5 stating rarity)

**Comment by martijnkersloot** [comment]
Not needed anymore, as discussed with Leo.
