### ISSUE TITLE
Mappings: check skos:closeMatch vs skos:exactMatch choices

### ISSUE THREAD

**Issue by brunasv** [brunasv/ISSVA#22]

**Comment by PhilipvD** [comment]
Some ISSVA classes match to SNOMED/ORDO/NCIt/HPO classes that seem to be a non-exact match, for example:
ISSVA:Angiokeratoma - SCT:Angiokeratoma (morphologic abnormality) AND SCT:Angiokeratoma of skin (disorder)

Those mappings can be given the skos:closeMatch property instead of skos:exactMatch
