### ISSUE TITLE
create description for ISSVA website

### ISSUE THREAD

**Issue by brunasv** [brunasv/ISSVA#27]
- what it is
- how to use (have to add to their databases, does not substitute classification)
- mention mappings to ordo 
- contact issva for issue reporting

**Comment by PhilipvD** [comment]
**What is the ISSVA ontology**
The ISSVA ontology has been created to represent a sharable semantic data model of the ISSVA classification. This ontological representation of the ISSVA classification is machine-readable and facilitates interoperability between systems that capture data about vascular anomalies. Its structured in a hierarchical manner and contains all concepts of the ISSVA classification and the relationships between them. The ontology is available in the Web Ontology Language (OWL) format. 

**How to use the ISSVA ontology**
The ISSVA ontology does not substitute the ISSVA classification, instead it should be used as an additional component to facilitate interoperability. Every concept in the ISSVA ontology has a unique code that should be attached to the corresponding data element. In the context of databases, the ISSVA ontology codes could be added as an extra column to the existing data. 

**Mappings to the Orphanet Rare Disease Ontology (ORDO)**
The ISSVA ontology contains machine-readable mappings to equivalent concepts in ORDO. This means that data annotated with codes from the ISSVA ontology are interoperable with data annotated with ORDO, without any extra effort, as long as there exists a mapping between the concepts.

**Issue reporting**
Please contact the ISSVA board in case you have any issues and/or feature requests for the ISSVA ontology. The ontology can then be updated accordingly.

**Comment by brunasv** [comment]
What is the ISSVA ontology?
The ISSVA ontology has been created to represent a sharable semantic data model of the ISSVA classification. This ontological representation of the ISSVA classification is machine-readable and facilitates interoperability between systems that capture data about vascular anomalies. It is structured hierarchically and contains all concepts of the ISSVA classification and the relationships between them. The ontology is available in the Web Ontology Language (OWL) format, and can be browsed here <https://bioportal.bioontology.org/ontologies/ISSVA>
How to use the ISSVA ontology
The ISSVA ontology does not substitute the ISSVA classification, instead, it should be used as an additional component to facilitate interoperability. Every concept in the ISSVA ontology has a unique code that should be attached to the corresponding data element. In the context of databases, the ISSVA ontology codes could be added as an extra column to the existing data. 
Mappings to other ontologies
The ISSVA ontology contains machine-readable mappings to equivalent concepts in other ontologies, namely: the Orphanet Rare Disease Ontology (ORDO), SNOMED Clinical Terms (SNOMED CT), National Cancer Institute thesaurus (NCIT), and the Human Phenotype Ontology (HPO). This means that data annotated with codes from the ISSVA ontology are interoperable with data annotated with the aforementioned ontologies, without any extra effort, as long as there exists a mapping between the concepts.
Issue reporting
Please contact the ISSVA board in case you have any issues and/or feature requests for the ISSVA ontology. The ontology can then be updated accordingly.
