### ISSUE TITLE
Add mappings to Protege ontology

### ISSUE THREAD

**Issue by martijnkersloot** [brunasv/ISSVA#4]
- Use skos:exactMatch
- Use original URIs

**Comment by brunasv** [comment]
mappings from Orphanet, HPO, etc.

**Comment by martijnkersloot** [comment]
Mappings:

https://docs.google.com/spreadsheets/d/1t-WoCsvMy-ZEQ_U1hFTrY-3nUviE0fap6NbLIStjGCo/edit?usp=sharing
