### ISSUE TITLE
Add hierarchy / relations to Protege ontology

### ISSUE THREAD

**Issue by martijnkersloot** [brunasv/ISSVA#5]

**Comment by brunasv** [comment]
## Anomalies Hierarchy
###  1. Malformations
- #### Simple
    -capillary malformations
    -lymphatic malformations
    -venous malformations
    -arteriovenous malformations
    -arteriovenous fistula
- #### Combined
    -CVM
    -CLM
    -LVM
    -CLVM
    -CAVM*
    -CLAVM*
    -others
- #### of major named vessels
- #### associated with other anomalies
### 2. Tumor 
- #### Benign
- #### Locally aggressive or borderline
- #### Malignant
## Relationship
### 1. Causal gene
## Properties
### 1. Anomalies of major vessels
    -number
    -diameter
    -valves
    -origin
    -origin
    -course
    -length
    -communication (AVF)
    -persistence (of embryonal vessel)
### 2. Affects
    -lymphatics
    -veins
    -arteries
    -capillaire (suggestion)
